//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KVALZAYTSEV.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Act
    {
        public int Id { get; set; }
        public string Description { get; set; }
        public int TypeOfMalfunctionId { get; set; }
        public int PhoneId { get; set; }
    
        public virtual Phone Phone { get; set; }
        public virtual TypeOfMalfunction TypeOfMalfunction { get; set; }
    }
}
